# UV Configuration for Multi-Agent Workflow Kit
# https://docs.astral.sh/uv/

cache-dir = ".uv-cache"

[pip]
# Use the default managed Python runtime (3.12 via .python-version)

# Build options
no-binary = []
only-binary = []

# Index configuration
index-url = "https://pypi.org/simple"
