# UV Configuration for Multi-Agent Workflow Kit
# https://docs.astral.sh/uv/

[pip]
# Use the system's Python installation
python-preference = "managed"

# Cache configuration
cache-dir = ".uv-cache"

# Build options
no-binary = []
only-binary = []

# Index configuration
index-url = "https://pypi.org/simple"

[cache]
# Enable caching for faster installations
enabled = true

# Cache directory (relative to project root)
dir = ".uv-cache"
